server:
  port: 8094

spring:
  application:
    name: cryptography-v1

configuration:
  error-messages:
    Default: No hemos podido realizar tu operación. Estamos trabajando para solucionar el inconveniente.

  cryptography:
    customers:
      aes: ${CUSTOMER_AES_KEY}
      rsa:
        private-key: ${CUSTOMER_RSA_PRIVATE_KEY}
        public-key: ${CUSTOMER_RSA_PUBLIC_KEY}
